import Head from 'next/head';
import Home from './home';

export default function Index() {
  return (
    <div className="">
      <Head>
        <title>Webeestech - eXStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/pp.jpg" />
      </Head>
      <Home />
    </div>
  );
}
